// AUTHENTICATE USER
export const CURRENT_USER = "CURRENT_USER";
export const CURRENT_USER_NULL = "CURRENT_USER_NULL";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_LOADING_GET_CURRENT_USER = "SET_LOADING_GET_CURRENT_USER";
export const SET_LOADING_EDIT_USER = "SET_LOADING_EDIT_USER";

// TEMP_CAMPAIGNS
export const ADD_TEMP_CAMPAIGN = "ADD_TEMP_CAMPAIGN";
export const EDIT_TEMP_CAMPAIGN = "EDIT_TEMP_CAMPAIGN";
export const DELETE_TEMP_CAMPAIGN = "DELETE_TEMP_CAMPAIGN";
export const GET_TEMP_CAMPAIGN = "GET_TEMP_CAMPAIGN";
export const SET_LOADING_ADD_TEMP_CAMPAIGN = "SET_LOADING_ADD_TEMP_CAMPAIGN";
export const SET_LOADING_GET_TEMP_CAMPAIGN = "SET_LOADING_GET_TEMP_CAMPAIGN";
