// AUTHENTICATE USER
export const CURRENT_USER = "CURRENT_USER";
export const CURRENT_USER_NULL = "CURRENT_USER_NULL";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_FAILED_NETWORK = "LOGIN_FAILED_NETWORK";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_FAILED_NETWORK = "REGISTER_FAILED_NETWORK";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const SET_LOADING_GET_CURRENT_USER = "SET_LOADING_GET_CURRENT_USER";
export const SET_LOADING_EDIT_USER = "SET_LOADING_EDIT_USER";
export const SET_LOADING_LOGIN = "SET_LOADING_LOGIN";
export const SET_LOADING_REGISTER = "SET_LOADING_REGISTER";

// TEMP_CAMPAIGNS
export const ADD_TEMP_CAMPAIGN = "ADD_TEMP_CAMPAIGN";
export const ADD_TEMP_CAMPAIGN_FAILED = "ADD_TEMP_CAMPAIGN_FAILED";
export const ADD_TEMP_CAMPAIGN_FAILED_NETWORK =
  "ADD_TEMP_CAMPAIGN_FAILED_NETWORK";
export const ADD_TEMP_CAMPAIGN_SUCCESS = "ADD_TEMP_CAMPAIGN_SUCCESS";
export const ADD_FAQ_SUCCESS = "ADD_FAQ_SUCCESS";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const FAQ_FAILED = "FAQ_FAILED";
export const FAQ_FAILED_NETWORK = "FAQ_FAILED_NETWORK";
export const TEMP_CAMPAIGN_CLOSE_SNACKBAR = "TEMP_CAMPAIGN_CLOSE_SNACKBAR";
export const EDIT_TEMP_CAMPAIGN = "EDIT_TEMP_CAMPAIGN";
export const DELETE_TEMP_CAMPAIGN = "DELETE_TEMP_CAMPAIGN";
export const GET_TEMP_CAMPAIGN = "GET_TEMP_CAMPAIGN";
export const SET_LOADING_ADD_TEMP_CAMPAIGN = "SET_LOADING_ADD_TEMP_CAMPAIGN";
export const SET_LOADING_FAQ = "SET_LOADING_FAQ";
export const SET_LOADING_GET_TEMP_CAMPAIGN = "SET_LOADING_GET_TEMP_CAMPAIGN";
